(begin
  (define width 800)
  (define height 600)
  (define x 69)
  (define y 200)
  (init-window width height)
  (define (frame) (
      if (window-should-close) 0 (begin
          (begin-drawing)
          (clear (* 255 (/ x width)) (* 255 (/ y height)) 0)
          (rect x y 20 20 0 255 0)
          (if (right-pressed) 
              (define x (+ x 0.01))
              (nop)
          )
          (if (left-pressed) 
              (define x (- x 0.01))
              (nop)
          )
          (if (up-pressed) 
              (define y (- y 0.01))
              (nop)
          )
          (if (down-pressed) 
              (define y (+ y 0.01))
              (nop)
          )
          (end-drawing)
          (frame)
        )
  ))
  (frame)

)
